In [1]:
import pandas as pd

books = pd.read_csv("books_cleaned.csv")

In [2]:
books["categories"].value_counts().reset_index()

                     categories  count
0                       Fiction   2111
1              Juvenile Fiction    390
2     Biography & Autobiography    311
3                       History    207
4            Literary Criticism    124
..                          ...    ...
474  Human-animal relationships      1
475                 Imperialism      1
476                  Aged women      1
477            Humorous stories      1
478                     Butlers      1

[479 rows x 2 columns]

In [4]:
books["categories"].value_counts().reset_index().query("count > 50")

                   categories  count
0                     Fiction   2111
1            Juvenile Fiction    390
2   Biography & Autobiography    311
3                     History    207
4          Literary Criticism    124
5                    Religion    117
6                  Philosophy    117
7     Comics & Graphic Novels    116
8                       Drama     86
9         Juvenile Nonfiction     57
10                    Science     56
11                     Poetry     51

In [5]:
books[books["categories"] == "Juvenile Fiction"]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,tagged_description
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,9780006646006 Joe and his parents are enjoying...
79,9780020442608,0020442602,The voyage of the Dawn Treader,Clive Staples Lewis,Juvenile Fiction,http://books.google.com/books/content?id=fDD3C...,"The ""Dawn Treader"" is the first ship Narnia ha...",1970.0,4.09,216.0,2869.0,"9780020442608 The ""Dawn Treader"" is the first ..."
85,9780030547744,0030547741,Where the Red Fern Grows,Wilson Rawls,Juvenile Fiction,http://books.google.com/books/content?id=IHpRw...,A young boy living in the Ozarks achieves his ...,2000.0,4.37,288.0,95.0,9780030547744 A young boy living in the Ozarks...
86,9780060000141,0060000147,Poppy's Return,Avi,Juvenile Fiction,http://books.google.com/books/content?id=XbcMJ...,"There's trouble at Gray House, the girlhood ho...",2006.0,3.99,256.0,1086.0,"9780060000141 There's trouble at Gray House, t..."
87,9780060001537,0060001534,Diary of a Spider,Doreen Cronin,Juvenile Fiction,http://books.google.com/books/content?id=UWvZo...,This is the diary ... of a spider. But don't b...,2005.0,4.25,40.0,7903.0,9780060001537 This is the diary ... of a spide...
...,...,...,...,...,...,...,...,...,...,...,...,...
4845,9781590385814,1590385810,Fablehaven,Brandon Mull,Juvenile Fiction,http://books.google.com/books/content?id=tbVIP...,When Kendra and Seth go to stay at their grand...,2006.0,4.09,351.0,111896.0,9781590385814 When Kendra and Seth go to stay ...
4930,9781596792500,1596792507,Sherlock Holmes and the Case of the Hound of t...,Arthur Conan Doyle;Malvina G. Vogel,Juvenile Fiction,http://books.google.com/books/content?id=EWgWP...,Sherlock Holmes and Dr. Watson travel to the b...,2005.0,4.51,237.0,28.0,9781596792500 Sherlock Holmes and Dr. Watson t...
4942,9781599900056,159990005X,The Drift House,Dale Peck,Juvenile Fiction,http://books.google.com/books/content?id=kbwPY...,Sent to stay with their uncle in a ship-like h...,2006.0,3.64,437.0,595.0,9781599900056 Sent to stay with their uncle in...
5010,9781844580514,1844580512,Attack of the Jaguar,M. A. Harvey,Juvenile Fiction,http://books.google.com/books/content?id=3HUdt...,This training manual for operatives of Xtreme ...,2004.0,3.40,125.0,4.0,9781844580514 This training manual for operati...
5157,9781932416374,1932416374,The Very Persistent Gappers of Frip,George Saunders;Lane Smith,Juvenile Fiction,http://books.google.com/books/content?id=xYJOP...,A novel set in the seaside village of Frip fol...,2006.0,4.11,84.0,2317.0,9781932416374 A novel set in the seaside villa...

In [6]:
books[books["categories"] == "Juvenile Nonfiction"]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,tagged_description
107,9780060277406,0060277408,The Secret Garden Cookbook,Amy Cotler,Juvenile Nonfiction,http://books.google.com/books/content?id=c7E_H...,Frances Hodgson Burnett's The Secret Garden de...,1999.0,4.28,128.0,142.0,9780060277406 Frances Hodgson Burnett's The Se...
108,9780060278427,0060278420,Laura's Album,William Anderson,Juvenile Nonfiction,http://books.google.com/books/content?id=_zTkq...,Though best known as the author of the Little ...,1998.0,4.30,80.0,713.0,9780060278427 Though best known as the author ...
228,9780060782139,0060782137,Time For Kids: Butterflies!,Editors of TIME For Kids,Juvenile Nonfiction,http://books.google.com/books/content?id=OdZxn...,"Butterflies There are 20,000 different kinds o...",2006.0,4.00,32.0,20.0,"9780060782139 Butterflies There are 20,000 dif..."
267,9780060882600,0060882603,The Annotated Charlotte's Web,E. B. White,Juvenile Nonfiction,http://books.google.com/books/content?id=vaYYH...,"Charlotte's Web, one of America's best-loved c...",2006.0,4.16,320.0,41.0,"9780060882600 Charlotte's Web, one of America'..."
434,9780064462044,0064462048,My Little House Crafts Book,Carolyn Strom Collins,Juvenile Nonfiction,http://books.google.com/books/content?id=lTzrs...,Make the same pioneer crafts that Laura did! I...,1998.0,4.05,64.0,56.0,9780064462044 Make the same pioneer crafts tha...
435,9780064462341,006446234X,Pioneer Girl,William Anderson,Juvenile Nonfiction,http://books.google.com/books/content?id=Sj4UD...,The pioneer spirit lives on... Readers around ...,2000.0,4.15,32.0,414.0,9780064462341 The pioneer spirit lives on... R...
439,9780066236179,0066236177,A Light in the Attic Book and CD,Shel Silverstein,Juvenile Nonfiction,http://books.google.com/books/content?id=FJfQs...,Last night while I lay thinking here Some What...,2001.0,4.34,176.0,590.0,9780066236179 Last night while I lay thinking ...
812,9780142302279,0142302279,Dirty Beasts,Roald Dahl,Juvenile Nonfiction,NaN,Poems tell the stories of a smart pig who outw...,2002.0,4.02,32.0,3953.0,9780142302279 Poems tell the stories of a smar...
821,9780142407226,0142407224,The Tough Guide to Fantasyland,Diana Wynne Jones,Juvenile Nonfiction,http://books.google.com/books/content?id=v5jxA...,A unique guide to fantasy literature helps rea...,2006.0,3.94,234.0,3897.0,9780142407226 A unique guide to fantasy litera...
823,9780142407929,0142407925,The BFG,Roald Dahl;David Wood;Jane Walmsley,Juvenile Nonfiction,http://books.google.com/books/content?id=aDf-O...,"With notes on staging, props, and costumes, a ...",2007.0,4.26,128.0,452.0,"9780142407929 With notes on staging, props, an..."
1014,9780198320272,0198320272,Julius Caesar,William Shakespeare,Juvenile Nonfiction,http://books.google.com/books/content?id=Nlmkh...,Caesar returns from a triumphant battle to Rom...,2001.0,3.67,128.0,133575.0,9780198320272 Caesar returns from a triumphant...
1074,9780237525378,0237525372,Oliver Twist,Pauline Francis;Charles Dickens,Juvenile Nonfiction,http://books.google.com/books/content?id=X6RvT...,This wonderful series is a quick way into a ra...,2003.0,3.66,48.0,92.0,9780237525378 This wonderful series is a quick...
1739,9780375812934,0375812938,Jurassic Park Institute Dinosaur Field Guide,Thomas R. Holtz;M. K. Brett-Surman,Juvenile Nonfiction,http://books.google.com/books/content?id=vW3hm...,Discusses dinosaur research and what can be le...,2001.0,4.08,160.0,2.0,9780375812934 Discusses dinosaur research and ...
1742,9780375823787,0375823786,Ancient Greece and the Olympics,Mary Pope Osborne;Natalie Pope Boyce,Juvenile Nonfiction,http://books.google.com/books/content?id=5cPbW...,"Filled with fascinating facts, a Magic Tree Ho...",2004.0,4.06,119.0,1044.0,"9780375823787 Filled with fascinating facts, a..."
1770,9780380732548,0380732548,Anne Frank,Johanna Hurwitz,Juvenile Nonfiction,http://books.google.com/books/content?id=3ja19...,"From July 1942 until August 1944, a young girl...",1999.0,3.99,64.0,143.0,9780380732548 From July 1942 until August 1944...
1972,9780395776087,0395776082,An American Plague,Jim Murphy,Juvenile Nonfiction,NaN,Recreates the devastation rendered to the city...,2003.0,3.80,165.0,3338.0,9780395776087 Recreates the devastation render...
2105,9780439314558,0439314550,Conversations with J.K. Rowling,Lindsey Fraser,Juvenile Nonfiction,http://books.google.com/books/content?id=Ly8dl...,From her birth in Chipping Sodbury near Bristo...,2001.0,3.99,96.0,4184.0,9780439314558 From her birth in Chipping Sodbu...
2117,9780439420068,0439420067,Eat!,Roberta Grobel Intrater,Juvenile Nonfiction,http://books.google.com/books/content?id=BnQ2n...,A group of babies enjoys some favorite foods--...,2002.0,3.95,10.0,54.0,9780439420068 A group of babies enjoys some fa...
2139,9780439736466,0439736463,"Where We Are, what We See",David Levithan,Juvenile Nonfiction,NaN,"A collection of poems, stories, essays, and ar...",2005.0,3.73,288.0,41.0,"9780439736466 A collection of poems, stories, ..."
2183,9780440229353,0440229359,How Angel Peterson Got His Name,Gary Paulsen,Juvenile Nonfiction,http://books.google.com/books/content?id=maJrL...,Author Gary Paulsen relates tales from his you...,2004.0,3.93,111.0,1139.0,9780440229353 Author Gary Paulsen relates tale...
2211,9780440419174,0440419174,Vincent Van Gogh,Jan Greenberg;Sandra Jane Jordan,Juvenile Nonfiction,http://books.google.com/books/content?id=n7kv9...,Profiles the turbulent life of Vincent van Gog...,2003.0,3.95,144.0,209.0,9780440419174 Profiles the turbulent life of V...
2320,9780448437439,0448437430,Who Was John F. Kennedy?,Yona Zeldis McDonough;Jill Weber,Juvenile Nonfiction,http://books.google.com/books/content?id=qjCzJ...,Chronicles the life of the president who saw A...,2004.0,4.19,112.0,598.0,9780448437439 Chronicles the life of the presi...
2323,9780448444826,0448444828,Who Was Anne Frank?,Ann Abramson,Juvenile Nonfiction,http://books.google.com/books/content?id=Bz37n...,Looks closely at Anne Frank's life before the ...,2007.0,4.26,103.0,1763.0,9780448444826 Looks closely at Anne Frank's li...
2503,9780486276809,0486276805,The Secret Garden Coloring Book,Frances Hodgson Burnett,Juvenile Nonfiction,http://books.google.com/books/content?id=sxHdA...,Ten-year-old Mary comes to live in a lonely ho...,2014.0,4.25,48.0,4.0,9780486276809 Ten-year-old Mary comes to live ...
2509,9780486296388,0486296385,Ballet Class Coloring Book,John Green;Caroline Denzler,Juvenile Nonfiction,http://books.google.com/books/content?id=p6PBk...,"Forty-two clear, accurate drawings (all in pro...",1997.0,3.64,48.0,11.0,"9780486296388 Forty-two clear, accurate drawin..."
2609,9780521618748,0521618746,Hamlet,William Shakespeare,Juvenile Nonfiction,http://books.google.com/books/content?id=5m2UP...,This edition of Hamlet is part of the groundbr...,2005.0,4.01,289.0,577429.0,9780521618748 This edition of Hamlet is part o...
2615,9780525469780,0525469788,"Boy, Were We Wrong about Dinosaurs!",Kathleen V. Kudlinski,Juvenile Nonfiction,http://books.google.com/books/content?id=QrRKD...,"Examines what is known about dinosaur bones, b...",2005.0,3.93,32.0,243.0,9780525469780 Examines what is known about din...
2858,9780590032490,0590032496,The witches,Roald Dahl,Juvenile Nonfiction,http://books.google.com/books/content?id=tpQxo...,"A young boy and his Norwegian grandmother, who...",1997.0,4.17,208.0,254867.0,9780590032490 A young boy and his Norwegian gr...
2859,9780590103879,0590103873,Expository Writing,Tara McCarthy,Juvenile Nonfiction,http://books.google.com/books/content?id=9HKHF...,A Down-to-Earth Approach James Henslin shares ...,1998.0,4.33,88.0,3.0,9780590103879 A Down-to-Earth Approach James H...
2897,9780618111206,0618111204,Once a Wolf,Stephen R. Swinburne;Jim Brandenburg,Juvenile Nonfiction,http://books.google.com/books/content?id=UkZWu...,With powerful and rare photos by a former phot...,2001.0,4.06,48.0,42.0,9780618111206 With powerful and rare photos by...
3133,9780679890522,0679890521,The Trail of Tears,Joseph Bruchac;Diana Magnuson,Juvenile Nonfiction,http://books.google.com/books/content?id=QxRUP...,"In 1838, settlers moving west forced the great...",1999.0,3.88,48.0,155.0,"9780679890522 In 1838, settlers moving west fo..."
3202,9780689833762,0689833768,Sad Underwear and Other Complications,Judith Viorst,Juvenile Nonfiction,http://books.google.com/books/content?id=e-sEA...,"Knock, knock. Who's there? Someone with sad un...",2000.0,3.87,80.0,104.0,"9780689833762 Knock, knock. Who's there? Someo..."
3203,9780689834196,0689834195,Salt in His Shoes,Deloris Jordan;Roslyn M. Jordan,Juvenile Nonfiction,http://books.google.com/books/content?id=hYzQw...,"Young Michael Jordan, who is smaller than the ...",2003.0,4.21,32.0,1054.0,"9780689834196 Young Michael Jordan, who is sma..."
3204,9780689835612,0689835612,Where Is Baby's Mommy?,Karen Katz,Juvenile Nonfiction,NaN,Is Mommy behind the chair? Is Mommy behind the...,2001.0,4.15,14.0,408.0,9780689835612 Is Mommy behind the chair? Is Mo...
3219,9780689869907,0689869908,Beatrice's Goat,Page McBrier,Juvenile Nonfiction,http://books.google.com/books/content?id=4MNED...,In this story based on a case from Project Hei...,2004.0,4.24,40.0,523.0,9780689869907 In this story based on a case fr...
3223,9780689876707,068987670X,Star Bright,Cathy Hapka,Juvenile Nonfiction,http://books.google.com/books/content?id=JPuiC...,PopTV is going to follow Star around for twent...,2005.0,3.67,160.0,3.0,9780689876707 PopTV is going to follow Star ar...
3263,9780723247791,072324779X,The Tale of The Flopsy Bunnies,Beatrix Potter,Juvenile Nonfiction,http://books.google.com/books/content?id=D2uQt...,"This original, authorised version has been lov...",2010.0,4.19,58.0,5051.0,"9780723247791 This original, authorised versio..."
3270,9780736805995,0736805990,"The Girlhood Diary of Louisa May Alcott, 1843-...",Louisa May Alcott,Juvenile Nonfiction,http://books.google.com/books/content?id=_dP35...,Excerpts from the girlhood diary of Louisa May...,2001.0,3.87,32.0,26.0,9780736805995 Excerpts from the girlhood diary...
3292,9780739844328,0739844326,Bill Gates,Sara Barton-Wood,Juvenile Nonfiction,http://books.google.com/books/content?id=Fr814...,"Presents the life of Bill Gates, from his chil...",2001.0,5.00,48.0,0.0,"9780739844328 Presents the life of Bill Gates,..."
3522,9780753459645,0753459647,I Wonder Why the Sun Rises,Brenda Walpole,Juvenile Nonfiction,http://books.google.com/books/content?id=SqpYs...,What is a leap year? Why are bees busy in summ...,2006.0,3.95,32.0,50.0,9780753459645 What is a leap year? Why are bee...
3552,9780756614195,0756614198,Star Wars,Kristin Lund;Simon Beecroft;Kerrie Dougherty,Juvenile Nonfiction,http://books.google.com/books/content?id=PAq2A...,Glorious full-color illustrations create a sea...,2005.0,4.30,175.0,128.0,9780756614195 Glorious full-color illustration...
3565,9780761417101,0761417109,The Star-Spangled Banner,Debra Hess,Juvenile Nonfiction,http://books.google.com/books/content?id=e-uzI...,Looks at the events leading up to the War of 1...,2003.0,4.00,40.0,1.0,9780761417101 Looks at the events leading up t...
3797,9780789458209,0789458209,Tree,David Burnie,Juvenile Nonfiction,http://books.google.com/books/content?id=Qwsqj...,Photographs and text explore the anatomy and l...,2000.0,4.07,64.0,5.0,9780789458209 Photographs and text explore the...
3798,9780791070482,0791070484,Bram Stoker's Dracula,Harold Bloom,Juvenile Nonfiction,http://books.google.com/books/content?id=vQ6SQ...,Presents a collection of critical essays on Br...,2003.0,3.83,243.0,6.0,9780791070482 Presents a collection of critica...
3799,9780791081266,0791081265,Edith Wharton's The Age of Innocence,Harold Bloom,Juvenile Nonfiction,http://books.google.com/books/content?id=MNuFk...,One of Edith Wharton's most critically acclaim...,2005.0,3.71,205.0,11.0,9780791081266 One of Edith Wharton's most crit...
3800,9780792241737,0792241738,Freedom Riders,Ann Bausum,Juvenile Nonfiction,http://books.google.com/books/content?id=JIlhQ...,Offers the true account of two young men who t...,2006.0,3.97,80.0,247.0,9780792241737 Offers the true account of two y...
3861,9780805069853,0805069852,You Come Too,Robert Frost,Juvenile Nonfiction,http://books.google.com/books/content?id=gZWM6...,An introduction to Robert Frost features an ab...,2002.0,4.16,92.0,77.0,9780805069853 An introduction to Robert Frost ...
3863,9780805071061,0805071067,Rosa,Nikki Giovanni,Juvenile Nonfiction,http://books.google.com/books/content?id=3pulA...,Provides the story of the black woman whose re...,2005.0,4.35,40.0,5942.0,9780805071061 Provides the story of the black ...
3921,9780810935204,0810935201,Lewis Carroll's Jabberwocky,Graeme Base,Juvenile Nonfiction,http://books.google.com/books/content?id=tyMFA...,Lewis Carroll's classic and inventive verse co...,1996.0,4.14,14.0,31.0,9780810935204 Lewis Carroll's classic and inve...
4069,9780822560562,0822560569,Barack Obama,Marlene Targ Brill,Juvenile Nonfiction,http://books.google.com/books/content?id=FIhyP...,Chronicles the life and career of the communit...,2006.0,3.96,48.0,19.0,9780822560562 Chronicles the life and career o...
4072,9780823410781,0823410781,A Picture Book of Anne Frank,NaN,Juvenile Nonfiction,http://books.google.com/books/content?id=CSNxW...,Traces the life of the young Jewish girl whose...,1993.0,4.17,32.0,208.0,9780823410781 Traces the life of the young Jew...
4409,9781400307845,1400307848,Writings to Young Women from Laura Ingalls Wil...,Laura Ingalls Wilder;Stephen W. Hines,Juvenile Nonfiction,http://books.google.com/books/content?id=e5gSD...,Using selections from her works and memoirs of...,2006.0,3.95,113.0,100.0,9781400307845 Using selections from her works ...
4596,9781560067849,1560067845,Flowers for Algernon,Patrice Cassedy,Juvenile Nonfiction,http://books.google.com/books/content?id=x_CUf...,"Discusses the young adult book ""Flowers for Al...",2000.0,3.00,96.0,1.0,"9781560067849 Discusses the young adult book ""..."
4744,9781580495868,1580495869,The Red Badge of Courage,Stephen Crane,Juvenile Nonfiction,http://books.google.com/books/content?id=lN1ga...,As he faces battle in the Civil War for the fi...,2004.0,3.23,170.0,74477.0,9781580495868 As he faces battle in the Civil ...
4808,9781586853334,1586853333,The Big Book of Boy Stuff,Bart King,Juvenile Nonfiction,http://books.google.com/books/content?id=08Ilm...,There's this boy. Let's say he's somewhere bet...,2004.0,4.24,292.0,141.0,9781586853334 There's this boy. Let's say he's...
5041,9781857232097,1857232097,The Fires of Heaven,Robert Jordan,Juvenile Nonfiction,http://books.google.com/books/content?id=4HyfQ...,The fifth book in Robert Jordan's internationa...,1994.0,4.15,912.0,106302.0,9781857232097 The fifth book in Robert Jordan'...
5142,9781931414166,1931414165,The Brooklyn Bridge,Elizabeth Mann;Alan Witschonke,Juvenile Nonfiction,http://books.google.com/books/content?id=s28MA...,Describes the construction of the Brooklyn Bri...,2006.0,4.44,46.0,35.0,9781931414166 Describes the construction of th...

In [8]:
category_mapping = {'Fiction' : "Fiction",
 'Juvenile Fiction': "Children's Fiction",
 'Biography & Autobiography': "Nonfiction",
 'History': "Nonfiction",
 'Literary Criticism': "Nonfiction",
 'Philosophy': "Nonfiction",
 'Religion': "Nonfiction",
 'Comics & Graphic Novels': "Fiction",
 'Drama': "Fiction",
 'Juvenile Nonfiction': "Children's Nonfiction",
 'Science': "Nonfiction",
 'Poetry': "Fiction"}

books["simple_categories"] = books["categories"].map(category_mapping)

In [9]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,9780002261982 A new 'Christie for Christmas' -...,NaN
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,9780006280897 Lewis' work on the nature of lov...,NaN
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,"9780006280934 ""In The Problem of Pain, C.S. Le...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,9788172235222 On A Train Journey Home To North...,NaN
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,9788173031014 This book tells the tale of a ma...,NaN
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,9788179921623 Wisdom to Create a Life of Passi...,NaN
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,9789027712059 Since the three volume edition o...,Nonfiction

In [10]:
books[~(books["simple_categories"].isna())]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,9780002005883 A NOVEL THAT READERS and critics...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,"9780006178736 A memorable, mesmerizing heroine...",Fiction
8,9780006482079,0006482074,Warhost of Vastmark,Janny Wurts,Fiction,http://books.google.com/books/content?id=uOL0f...,"Tricked once more by his wily half-brother, Ly...",1995.0,4.03,522.0,2966.0,9780006482079 Tricked once more by his wily ha...,Fiction
30,9780006646006,000664600X,Ocean Star Express,Mark Haddon;Peter Sutton,Juvenile Fiction,http://books.google.com/books/content?id=I2QZA...,Joe and his parents are enjoying a summer holi...,2002.0,3.50,32.0,1.0,9780006646006 Joe and his parents are enjoying...,Children's Fiction
46,9780007121014,0007121016,Taken at the Flood,Agatha Christie,Fiction,http://books.google.com/books/content?id=3gWlx...,A Few Weeks After Marrying An Attractive Young...,2002.0,3.71,352.0,8852.0,9780007121014 A Few Weeks After Marrying An At...,Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5178,9781933648279,1933648279,Night Has a Thousand Eyes,Cornell Woolrich,Fiction,http://books.google.com/books/content?id=3Gk6s...,"""Cornell Woolrich's novels define the essence ...",2007.0,3.77,344.0,680.0,"9781933648279 ""Cornell Woolrich's novels defin...",Fiction
5188,9784770028969,4770028962,Coin Locker Babies,村上龍,Fiction,http://books.google.com/books/content?id=87DJw...,Rescued from the lockers in which they were le...,2002.0,3.75,393.0,5560.0,9784770028969 Rescued from the lockers in whic...,Fiction
5189,9788122200850,8122200850,"Cry, the Peacock",Anita Desai,Fiction,http://books.google.com/books/content?id=_QKwV...,This book is the story of a young girl obsesse...,1980.0,3.22,218.0,134.0,9788122200850 This book is the story of a youn...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,9789027712059 Since the three volume edition o...,Nonfiction

In [11]:
from transformers import pipeline

fiction_categories = ["Fiction", "Nonfiction"]

pipe = pipeline("zero-shot-classification",
                model="facebook/bart-large-mnli",
                device="cuda")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:112: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/1.15k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/515 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

In [12]:
sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[0]

In [13]:
pipe(sequence, fiction_categories)

{'sequence': 'A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.',
 'labels': ['Fiction', 'Nonfiction'],
 'scores': [0.8438267111778259, 0.15617327392101288]}

In [14]:
import numpy as np

max_index = np.argmax(pipe(sequence, fiction_categories)["scores"])
max_label = pipe(sequence, fiction_categories)["labels"][max_index]
max_label

'Fiction'

In [15]:
def generate_predictions(sequence, categories):
    predictions = pipe(sequence, categories)
    max_index = np.argmax(predictions["scores"])
    max_label = predictions["labels"][max_index]
    return max_label

In [18]:
from tqdm import tqdm

actual_cats = []
predicted_cats = []

for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Fiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Fiction"]

100%|██████████| 300/300 [00:26<00:00, 11.52it/s]

In [17]:
for i in tqdm(range(0, 300)):
    sequence = books.loc[books["simple_categories"] == "Nonfiction", "description"].reset_index(drop=True)[i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    actual_cats += ["Nonfiction"]

100%|██████████| 300/300 [00:25<00:00, 11.64it/s]

In [20]:
predictions_df = pd.DataFrame({"actual_categories": actual_cats, "predicted_categories": predicted_cats})

In [21]:
predictions_df

    actual_categories predicted_categories
0             Fiction              Fiction
1             Fiction              Fiction
2             Fiction              Fiction
3             Fiction           Nonfiction
4             Fiction              Fiction
..                ...                  ...
295           Fiction           Nonfiction
296           Fiction              Fiction
297           Fiction           Nonfiction
298           Fiction              Fiction
299           Fiction              Fiction

[300 rows x 2 columns]

In [22]:
predictions_df["correct_prediction"] = (
    np.where(predictions_df["actual_categories"] == predictions_df["predicted_categories"], 1, 0)
)

In [23]:
predictions_df["correct_prediction"].sum() / len(predictions_df)

np.float64(0.68)

In [24]:
isbns = []
predicted_cats = []

missing_cats = books.loc[books["simple_categories"].isna(), ["isbn13", "description"]].reset_index(drop=True)

In [25]:
for i in tqdm(range(0, len(missing_cats))):
    sequence = missing_cats["description"][i]
    predicted_cats += [generate_predictions(sequence, fiction_categories)]
    isbns += [missing_cats["isbn13"][i]]

100%|██████████| 1454/1454 [02:04<00:00, 11.65it/s]

In [26]:
missing_predicted_df = pd.DataFrame({"isbn13": isbns, "predicted_categories": predicted_cats})

In [28]:
missing_predicted_df

             isbn13 predicted_categories
0     9780002261982              Fiction
1     9780006280897           Nonfiction
2     9780006280934           Nonfiction
3     9780006380832           Nonfiction
4     9780006470229              Fiction
...             ...                  ...
1449  9788125026600           Nonfiction
1450  9788171565641              Fiction
1451  9788172235222              Fiction
1452  9788173031014           Nonfiction
1453  9788179921623              Fiction

[1454 rows x 2 columns]

In [29]:
books = pd.merge(books, missing_predicted_df, on="isbn13", how="left")
books["simple_categories"] = np.where(books["simple_categories"].isna(), books["predicted_categories"], books["simple_categories"])
books = books.drop(columns = ["predicted_categories"])

In [30]:
books

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,tagged_description,simple_categories
0,9780002005883,0002005883,Gilead,Marilynne Robinson,Fiction,http://books.google.com/books/content?id=KQZCP...,A NOVEL THAT READERS and critics have been eag...,2004.0,3.85,247.0,361.0,9780002005883 A NOVEL THAT READERS and critics...,Fiction
1,9780002261982,0002261987,Spider's Web,Charles Osborne;Agatha Christie,Detective and mystery stories,http://books.google.com/books/content?id=gA5GP...,A new 'Christie for Christmas' -- a full-lengt...,2000.0,3.83,241.0,5164.0,9780002261982 A new 'Christie for Christmas' -...,Fiction
2,9780006178736,0006178731,Rage of angels,Sidney Sheldon,Fiction,http://books.google.com/books/content?id=FKo2T...,"A memorable, mesmerizing heroine Jennifer -- b...",1993.0,3.93,512.0,29532.0,"9780006178736 A memorable, mesmerizing heroine...",Fiction
3,9780006280897,0006280897,The Four Loves,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=XhQ5X...,Lewis' work on the nature of love divides love...,2002.0,4.15,170.0,33684.0,9780006280897 Lewis' work on the nature of lov...,Nonfiction
4,9780006280934,0006280935,The Problem of Pain,Clive Staples Lewis,Christian life,http://books.google.com/books/content?id=Kk-uV...,"""In The Problem of Pain, C.S. Lewis, one of th...",2002.0,4.09,176.0,37569.0,"9780006280934 ""In The Problem of Pain, C.S. Le...",Nonfiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5192,9788172235222,8172235224,Mistaken Identity,Nayantara Sahgal,Indic fiction (English),http://books.google.com/books/content?id=q-tKP...,On A Train Journey Home To North India After L...,2003.0,2.93,324.0,0.0,9788172235222 On A Train Journey Home To North...,Fiction
5193,9788173031014,8173031010,Journey to the East,Hermann Hesse,Adventure stories,http://books.google.com/books/content?id=rq6JP...,This book tells the tale of a man who goes on ...,2002.0,3.70,175.0,24.0,9788173031014 This book tells the tale of a ma...,Nonfiction
5194,9788179921623,817992162X,The Monk Who Sold His Ferrari: A Fable About F...,Robin Sharma,Health & Fitness,http://books.google.com/books/content?id=c_7mf...,"Wisdom to Create a Life of Passion, Purpose, a...",2003.0,3.82,198.0,1568.0,9788179921623 Wisdom to Create a Life of Passi...,Fiction
5195,9788185300535,8185300534,I Am that,Sri Nisargadatta Maharaj;Sudhakar S. Dikshit,Philosophy,http://books.google.com/books/content?id=Fv_JP...,This collection of the timeless teachings of o...,1999.0,4.51,531.0,104.0,9788185300535 This collection of the timeless ...,Nonfiction
5196,9789027712059,9027712050,The Berlin Phenomenology,Georg Wilhelm Friedrich Hegel,History,http://books.google.com/books/content?id=Vy7Sk...,Since the three volume edition ofHegel's Philo...,1981.0,0.00,210.0,0.0,9789027712059 Since the three volume edition o...,Nonfiction

In [31]:
books[books["categories"].str.lower().isin([
    "romance",
    "science fiction",
    "scifi",
    "fantasy",
    "horror",
    "mystery",
    "thriller",
    "comedy",
    "crime",
    "historical"
])]

,isbn13,isbn10,title,authors,categories,thumbnail,description,published_year,average_rating,num_pages,ratings_count,tagged_description,simple_categories
24,9780006513087,0006513085,Gravity,Tess Gerritsen,Science fiction,http://books.google.com/books/content?id=KI66c...,Emma Watson a research physician has been trai...,2004.0,4.04,342.0,8024.0,9780006513087 Emma Watson a research physician...,Nonfiction
475,9780099410355,0099410354,Traitor,Matthew Woodring Stover,Science fiction,http://books.google.com/books/content?id=VbICO...,"From the depths of catastrophe, a glimmer of h...",2002.0,4.00,320.0,6765.0,"9780099410355 From the depths of catastrophe, ...",Fiction
478,9780099422341,0099422344,Yeats is Dead!,Joseph O'Connor,Comedy,http://books.google.com/books/content?id=DrE3I...,"In aid of Amnesty International, this is a bri...",2002.0,3.39,298.0,34.0,"9780099422341 In aid of Amnesty International,...",Fiction
491,9780099446729,0099446723,Blackwood Farm,Anne Rice,Horror,http://books.google.com/books/content?id=cIn8T...,"Lestat Is Back, Saviour And Demon, Presiding O...",2003.0,3.86,774.0,26145.0,"9780099446729 Lestat Is Back, Saviour And Demo...",Fiction
1090,9780261102422,0261102427,The Silmarillion,John Ronald Reuel Tolkien,Fantasy,http://books.google.com/books/content?id=22ePu...,Tolkien's Silmarillion is the core work of the...,1999.0,3.91,384.0,253.0,9780261102422 Tolkien's Silmarillion is the co...,Fiction
1435,9780340837955,0340837950,Stranger in a Strange Land,Robert A. Heinlein,Science fiction,http://books.google.com/books/content?id=ZQhiP...,"Epic, entertaining, Stranger in a Strange Land...",2005.0,3.92,672.0,563.0,"9780340837955 Epic, entertaining, Stranger in ...",Fiction
1439,9780345251220,0345251229,Visions from Nowhere,William Arrow,Science fiction,NaN,"The first novel in the series, ""Return to the ...",1976.0,3.23,183.0,10.0,"9780345251220 The first novel in the series, ""...",Fiction
2845,9780575075597,0575075597,Replay,Ken Grimwood,Fantasy,http://books.google.com/books/content?id=9vmNP...,At forty-three Jeff Winston is tired of his lo...,2005.0,4.16,272.0,412.0,9780575075597 At forty-three Jeff Winston is t...,Fiction
2860,9780590254762,0590254766,"The lion, the witch and the wardrobe",Clive Staples Lewis,Fantasy,NaN,Four English school children enter the magic l...,1995.0,4.21,189.0,860.0,9780590254762 Four English school children ent...,Nonfiction
3288,9780739423851,0739423851,Wizard's Castle,Diana Wynne Jones,Fantasy,http://books.google.com/books/content?id=hB7hA...,Howl's moving castle - Eldest of three sisters...,2002.0,4.44,376.0,439.0,9780739423851 Howl's moving castle - Eldest of...,Fiction
3289,9780739439708,0739439707,Time Quartet,Madeleine L'Engle,Science fiction,NaN,"Blending magic with quantum physics, Madeleine...",2003.0,4.35,646.0,165.0,9780739439708 Blending magic with quantum phys...,Fiction
3563,9780760728505,076072850X,"20,000 Leagues Under the Sea",Jules Verne,Science fiction,NaN,Retells the adventures of a French professor a...,2002.0,3.88,394.0,135778.0,9780760728505 Retells the adventures of a Fren...,Fiction
4483,9781416502043,1416502041,The Voyage of the Jerle Shannara Trilogy,Terry Brooks,Fantasy,http://books.google.com/books/content?id=jqVsA...,When the body of a half-drowned elf is found f...,2004.0,4.26,1260.0,84.0,9781416502043 When the body of a half-drowned ...,Fiction
4979,9781841494081,1841494089,The Darkness that Comes Before,R. Scott Bakker,Fantasy,http://books.google.com/books/content?id=BG8qG...,A score of centuries has passed since the Firs...,2005.0,3.79,638.0,317.0,9781841494081 A score of centuries has passed ...,Nonfiction
5040,9781857231359,185723135X,Use of Weapons,Iain Banks,Science fiction,NaN,The man known as Cheradenine Zakalwe was one o...,1992.0,4.19,411.0,30779.0,9781857231359 The man known as Cheradenine Zak...,Nonfiction
5057,9781857989342,1857989341,The Gods Themselves,Isaac Asimov,Science fiction,http://books.google.com/books/content?id=8ClIP...,"In the year 2100, mankind on Earth, settlers i...",2000.0,4.09,288.0,41304.0,"9781857989342 In the year 2100, mankind on Ear...",Fiction

In [32]:
books[books["categories"].str.lower().isin([
    "romance",
    "science fiction",
    "scifi",
    "fantasy",
    "horror",
    "mystery",
    "thriller",
    "comedy",
    "crime",
    "historical"
])].shape

(16, 13)

In [34]:
books.to_csv("books_with_categories.csv", index=False)